name: Build from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ШАГ 01 — Скачать код
        uses: actions/checkout@v4

      - name: ШАГ 02 — Установить unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: ШАГ 03 — Распаковать ZIP
        run: unzip -o GameLauncher_fixed.zip -d .

      - name: ШАГ 04 — Найти корень проекта и экспортировать переменную PROJ
        run: |
          if [ -d "app/src/main" ]; then
            echo "PROJ=." >> $GITHUB_ENV
          elif [ -d "GameLauncher/app/src/main" ]; then
            echo "PROJ=GameLauncher" >> $GITHUB_ENV
          else
            echo "Не найден проект (нет app/src/main)"; exit 1
          fi

      - name: ШАГ 05 — Установить JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: ШАГ 05.1 — Установить Gradle 8.7
        uses: gradle/actions/setup-gradle@v3

      - name: ШАГ 06 — Поставить платформу и инструменты Android 33
        uses: android-actions/setup-android@v2
        with:
          packages: |
            platforms;android-33
            build-tools;33.0.1

      - name: ШАГ 07 — Включить AndroidX и JVM args (на всякий случай)
        run: |
          echo "android.useAndroidX=true"       >> "$PROJ/gradle.properties"
          echo "android.enableJetifier=true"    >> "$PROJ/gradle.properties"
          echo "org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8" >> "$PROJ/gradle.properties"
          sed -n '1,200p' "$PROJ/gradle.properties"

      - name: ШАГ 08 — Сгенерировать Gradle Wrapper 8.7
        run: |
          cd "$PROJ"
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew

      - name: ШАГ 09 — Сборка DEBUG (подробные логи)
        run: |
          cd "$PROJ"
          ./gradlew assembleDebug --stacktrace --warning-mode all

      - name: ШАГ 10 — Сборка RELEASE (подробные логи)
        run: |
          cd "$PROJ"
          ./gradlew assembleRelease --stacktrace --warning-mode all

      - name: ШАГ 11 — Найти APK и переименовать
        id: findapk
        run: |
          set -e
          cd "$PROJ"
          APK="$(ls -1 app/build/outputs/apk/debug/*.apk 2>/dev/null || true)"
          [ -z "$APK" ] && APK="$(ls -1 app/build/outputs/apk/release/*.apk 2>/dev/null || true)"
          if [ -z "$APK" ]; then
            echo "APK не найден"; exit 1
          fi
          cp "$APK" GameLauncher.apk
          echo "apk_path=$PWD/GameLauncher.apk" >> $GITHUB_OUTPUT

      - name: ШАГ 12 — Сохранить APK
        uses: actions/upload-artifact@v4
        with:
          name: GameLauncher-APK
          path: ${{ steps.findapk.outputs.apk_path }}

      - name: ШАГ 13 — Сохранить журналы сборки (если упадёт)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            **/build/**/reports/**
            **/build/**/outputs/**
            **/build/**/logs/**
